#!/data/data/com.termux/files/usr/bin/bash


# Auto Install Tools

# Username: MrXerxesID

# Hostname: Projoki

# FB: Risa Permana

# E-mail: projoki.tv@gmail.com

# Telp/Fax: +6283120027137

# Website: https://projoki.blogspot.com

# Channel: Projoki. TV

# Like Comment And Subscribe


# Bersihkan Layar

clear


#This colour

blue='\e[0;34'

cyan='\e[0;36m'

green='\e[0;34m'

okegreen='\033[92m'

lightgreen='\e[1;32m'

white='\e[1;37m'

red='\e[1;31m'

yellow='\e[1;33m'


###################################################

# CTRL C

###################################################

trap ctrl_c INT

ctrl_c() {

clear

echo -e $red"[#]> (Ctrl + C ) Detected, Trying To Exit ... "

sleep 1

echo ""

echo -e $yellow"[#]> Thank You For Using My Tools ... "

sleep 1

echo ""

echo -e $white"[#]> Im Here ... "

read enter

exit

}


# Isi oc :*

echo ""

echo -e $white" ***********************************************"                          

echo -e $cyan" Toolkit For$red Lazy People"

echo -e $cyan" Tools Recoded by$red MrXerXesID"

echo -e $cyan" Follow Me On Github:$red @projoki"

echo -e $cyan" My Site:$red https://projoki.blogspot.com"

echo -e $cyan" Contact Me In:$red projoki.tv@gmail.com"

echo -e $cyan" Made $red 16-07-2018"

echo -e $cyan" Team: $red INA BLACK HAT"


echo -e $white" ***********************************************"

echo ""

echo -e $red" 01) Tool Spam LITESPAM"

echo -e $red" 2) OSIF

echo -e $red" 3) Exit "

read -p "[Projoki@Tools]> " act;


if [ $act = 1 ] || [ $act = 01 ]

then

clear

echo -e $red" Installing Tools Spam LITESPAM "

sleep 1

apt update && apt upgrade

apt install php

pkg install git

git clone https://github.com/4L13199/LITESPAM

echo -e $red" T E R I N S T A L L "

fi


if [ $act = 2 ] || [ $act = 2 ]

then

clear

echo -e $red" Installing OSIF "

sleep 1

apt update && apt upgrade

apt install php

pkg install git

git clone https://github.com/projoki/OSIF-Projoki

echo -e $red" T E R I N S T A L L "

if [ $act = 3 ] || [ $act = 3 ]

fi

then

echo " Ko Udahan Sih     "

sleep 1

echo " Lagi Sibuk Ya?      "

sleep 1

echo " Yaudah Kalo Gitu     "

sleep 1

echo " Hati-hati Dijalan     "

sleep 1

echo " Sampai Ketemu Lagi      "

sleep 1

echo " Byee Byee :*       "

sleep 1

exit

fi
